// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAndSavePortfolioDescriptorForImage(arg1, arg2) {
  return window['go']['main']['App']['CreateAndSavePortfolioDescriptorForImage'](arg1, arg2);
}

export function CreateImageDescriptor(arg1) {
  return window['go']['main']['App']['CreateImageDescriptor'](arg1);
}

export function GetImagePreview(arg1) {
  return window['go']['main']['App']['GetImagePreview'](arg1);
}

export function LoadDemoSeller(arg1) {
  return window['go']['main']['App']['LoadDemoSeller'](arg1);
}

export function ReturnTagsForImage(arg1) {
  return window['go']['main']['App']['ReturnTagsForImage'](arg1);
}

export function SaveNewSellerTag(arg1, arg2) {
  return window['go']['main']['App']['SaveNewSellerTag'](arg1, arg2);
}

export function SearchFromImageDescriptor(arg1) {
  return window['go']['main']['App']['SearchFromImageDescriptor'](arg1);
}

export function SendBuyerChatMessage(arg1) {
  return window['go']['main']['App']['SendBuyerChatMessage'](arg1);
}

export function SendSellerChatMessage(arg1) {
  return window['go']['main']['App']['SendSellerChatMessage'](arg1);
}
