// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAndSavePortfolioDescriptorForImage(arg1:number,arg2:string):Promise<void>;

export function CreateImageDescriptor(arg1:string):Promise<string>;

export function GetImagePreview(arg1:string):Promise<string>;

export function LoadDemoSeller(arg1:number):Promise<main.Profile>;

export function ReturnTagsForImage(arg1:string):Promise<Array<string>>;

export function SaveNewSellerTag(arg1:number,arg2:string):Promise<void>;

export function SearchFromImageDescriptor(arg1:string):Promise<Array<main.Profile>>;

export function SendBuyerChatMessage(arg1:string):Promise<main.BuyerChatResponse>;

export function SendSellerChatMessage(arg1:string):Promise<Array<string>>;
